/*********************
 * Name : wordfoot.h *
 *********************/

int main (VOID);

// Wert fÅr Fenster
#define ID_ClientWindow         1

#define IDB_Platz               50

// Werte fÅr MenÅ
#define IDM_File        10
#define IDM_Choose      11
#define IDM_Exit        13

#define IDM_Play        20

#define IDM_Options     21

#define IDM_About       90 
#define IDM_Help        91
#define IDM_Info        92

// Werte fÅr Nachrichten
#define ID_Ani          40

// Werte fÅr Timer
#define ID_Timer1       60
#define ID_Timer2       61

// Werte fÅr Dialog
#define ID_Dialog       100
#define ID_Aufg         101
#define ID_Wort         102
#define ID_Eing         103

// Werte fÅr Optionen
#define ID_Option     200
#define ID_Text       201
#define ID_Reihe       202
#define ID_Zufall       203

